version: "3.8"

services:
  e2e-web-server:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:password@e2e-database:5432/postgres
    ports:
      - 5999:3000
    depends_on:
      - e2e-database
    develop:
      watch:
        - action: rebuild
          path: ./

  e2e-database:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=password
